In [1]:
import numpy as np

# Q1) construct 1d numpy array, 2d numpy array,3d numpy array.

In [7]:
d1=np.ones(5)
print(d1)
d2=np.random.randint(-100, 100, (4,3))
print(d2)
d3=np.random.randint(-100, 100, (3,3,3))
print(d3)

[1. 1. 1. 1. 1.]
[[-67  82  94]
 [-23  89 -53]
 [ -7  -1  65]
 [-82  31  28]]
[[[-93  12   2]
  [ 39  70 -65]
  [ 94  89  71]]

 [[-87 -35 -94]
  [ 31 -27  55]
  [-39 -46  84]]

 [[ 52  94  28]
  [-66 -69 -40]
  [-52  17 -12]]]


# Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()

In [11]:
x=np.array([1,2,3,5,6])
x1=np.zeros(5)
print (x)
print(x1)
# Test whether any of the elements of a given array is non-zero:
print(np.any(x))
print(np.any(x1))

[1 2 3 5 6]
[0. 0. 0. 0. 0.]
True
False


# Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives

In [15]:
s0=np.zeros(10)
print(s0)
s1=np.ones(10)
print(s1)
s5=5*np.ones(10)
print(s5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Q4- Write a NumPy program to create an array of 10 zeros 3d

In [19]:
a_3d_array = np.zeros((10, 10, 10))
print(a_3d_array)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0

# Q5- Write a NumPy program to create an array of the integers from 30 to 70

In [22]:
y=np.arange(30,71) # we assume 70 is included
y

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# Q6- Write a NumPy program to create a 3x3 identity matrix

In [23]:
# we use identity method
id=np.identity(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Q7- Write a NumPy program to generate a random number between 0 and 1.

In [40]:
r=np.random.random(1)
r

array([0.64047563])

# Q8- Write a NumPy program to create a 3X4 array using and iterate over it

In [45]:
q8=np.arange(0,12).reshape(3,4)
print(q8)
for i in range (3):
  for j in range(4):
    print(q8[i][j])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


# Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [49]:
s10=np.ones(100).reshape(10,10)
print(s10)
print("after making borders only equal one///////////////////")
s10[1:-1,1:-1]=0
print(s10)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
after making borders only equal one///////////////////
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
